### ISSUE TITLE
Checking if the DNS response is valid

### ISSUE THREAD

**Issue by wjayesh** [wjayesh/coredns-healthcheck#8]
Currently, we can query the CoreDNS pods and services to resolve service names. I am using the `kubernetes.default` service as a question to test the DNS service. 
How should we determine if the pods are healthy based on the response recieved?

A few cases I can think of when the pods can be considered unhealthy:

1) If there's an `i/o timeout` in the response. 
2) If the status is something other than `NOERROR`. (This is because the pods should be able to resolve the `kubernetes` service in any case.)

Are there any other situations or indicators we can use to test the output against?

**Comment by wjayesh** [comment]
Here is a screenshot with a sample response:

![](https://user-images.githubusercontent.com/37150991/84260469-b9624e80-ab37-11ea-8a53-a4e3f8d95875.png)

**Comment by wjayesh** [comment]
@yongtang @greenpau

**Comment by yongtang** [comment]
@wjayesh yes `i/o timeout` is a very good indicator for almost all failure cases in udp space. This could be caused by network outage, server failed to response, etc.
`NOERROR` is another indicator.

One more case, which helps to figure out what went wrong, is to try from different network path:
- send query from inside coredns pods to 127.0.0.1 (check to see if coredns process is ok).
- send query from inside coredns pods to public facing IP (check to see if public facing ip is accessible by itself.).
- send query from outside coredns pods to public facing IP. (check to see if public facing ip is accessible by others)

**Comment by wjayesh** [comment]
I will be adding the checks you suggested with the new version where the binary is now going to be deployed on the host. This will give it access to all network namespaces and then we could carry out those operations.
